import 'package:flutter/material.dart';

class ReportScreen extends StatelessWidget {
  const ReportScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: const Color(0xFF4B2E83),
        title: const Text('Report'),
        leading: const BackButton(),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(12),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _headerSection(),
            _card(
              title: 'Client Information',
              child: _table([
                ['Client Name', 'Niharika Kaushik'],
                ['Age/Gender', '26/Female'],
                ['Contact', '+91 XXXXXXXXXX'],
                ['Email', 'niharika@gmail.com'],
                ['Address', 'Meerut, UP, India'],
              ]),
            ),
            _card(
              title: 'Loan Details',
              child: _table([
                ['Loan Type', 'Business Loan'],
                ['Application ID', 'BL-2025'],
                ['Requested Amount', '₹5,00,000'],
                ['Tenure', '3 years'],
                ['Interest Rate', '9.75% p.a.'],
                ['Repayment Type', 'Monthly EMI'],
                ['Application Mode', 'Online Submission'],
              ]),
            ),
            _card(
              title: 'Lead Source & Assignment',
              child: _table([
                ['Lead Source', 'Website Form'],
                ['Lead Date', '04 November 2025'],
                ['Assigned to', 'Rahul Mishra'],
                ['Follow-up date', '08 November 2025, 10:00 AM'],
                ['Priority Level', 'HIGH'],
              ]),
            ),
            _card(
              title: 'Communication Log',
              child: _table(
                [
                  ['4 Nov 2025', 'Email', 'Automated acknowledgment sent'],
                  ['5 Nov 2025', 'Call', 'No response'],
                  [
                    '6 Nov 2025',
                    'Call',
                    'Client answered, discussed expansion needs',
                  ],
                ],
                headers: ['Date', 'Mode', 'Summary'],
              ),
            ),
            _card(
              title: 'Verification Status',
              child: Column(
                children: [
                  _statusRow(
                    'Identity Verification (KYC)',
                    'Completed',
                    'Aadhaar and PAN verified',
                    Colors.green,
                  ),
                  _statusRow(
                    'Business Registration',
                    'In Process',
                    'GST certificate under review',
                    Colors.orange,
                  ),
                  _statusRow(
                    'Credit Check',
                    'Approved',
                    'Score: 782',
                    Colors.green,
                  ),
                ],
              ),
            ),
            _card(
              title: 'Feedback and Notes',
              child: const Text(
                'Client was well-informed about loan procedures. '
                'Interested in flexible repayment and prepayment options. '
                'Follow-up required once verification is complete.',
              ),
            ),
            _card(
              title: 'Next Steps',
              child: const Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('• Prepare sanction letter draft by 08 Nov 2025'),
                  Text('• Schedule digital signing appointment'),
                  Text(
                    '• Update client via email once the file is forwarded to the loan officer',
                  ),
                ],
              ),
            ),
            const SizedBox(height: 20),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF4B2E83),
                  padding: const EdgeInsets.symmetric(vertical: 14),
                ),
                onPressed: () {},
                child: const Text('Download PDF'),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _headerSection() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: const [
        Text(
          'CRM Report — Loan Application Summary',
          style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
        ),
        SizedBox(height: 4),
        Text('Report Date: 06 November 2025'),
        Text('Generated By: Meerut Skills CRM'),
        Text('Department: Loan Management'),
        SizedBox(height: 12),
      ],
    );
  }

  Widget _card({required String title, required Widget child}) {
    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
      child: Padding(
        padding: const EdgeInsets.all(12),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              title,
              style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
            ),
            const Divider(),
            child,
          ],
        ),
      ),
    );
  }

  Widget _table(List<List<String>> rows, {List<String>? headers}) {
    return Table(
      columnWidths: const {0: FlexColumnWidth(2), 1: FlexColumnWidth(3)},
      border: TableBorder.all(color: Colors.grey.shade300),
      children: [
        if (headers != null)
          TableRow(
            decoration: BoxDecoration(color: Colors.grey.shade200),
            children: headers
                .map(
                  (h) => Padding(
                    padding: const EdgeInsets.all(8),
                    child: Text(
                      h,
                      style: const TextStyle(fontWeight: FontWeight.bold),
                    ),
                  ),
                )
                .toList(),
          ),
        ...rows.map(
          (row) => TableRow(
            children: row
                .map(
                  (cell) => Padding(
                    padding: const EdgeInsets.all(8),
                    child: Text(cell),
                  ),
                )
                .toList(),
          ),
        ),
      ],
    );
  }

  Widget _statusRow(String step, String status, String remark, Color color) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 6),
      child: Row(
        children: [
          Expanded(child: Text(step)),
          Chip(
            label: Text(status),
            backgroundColor: color.withOpacity(0.15),
            labelStyle: TextStyle(color: color),
          ),
          const SizedBox(width: 8),
          Expanded(child: Text(remark)),
        ],
      ),
    );
  }
}
